### PR TITLE
Fixed directory permissions issue for alpine-consul-ui

### PR DESCRIPTION
**Pull request by yvann**
Hi, thank you for all your images, I just found a small issue for consul-ui.

```
consului_1 | ==> Starting Consul agent...
consului_1 | ==> Error starting agent: Failed to start Consul client: Failed to start lan serf: mkdir /data/serf: permission denied
```

### CODE REVIEW

**Comment by smebberson** [comment]
@yvann, thanks for your PR!

We actually found that issue today too. I did include a commit (https://github.com/smebberson/docker-alpine/commit/19302c7c609288798795d0bb5f4c6ec3d799800b), only 6 hours ago which includes a working fix for this. Is it possible you tested this, prior to my last commit, but your fork actually included the commit?

Because we tested the latest commit and it works... perhaps you could rebuild the image from scratch and double check?

Thank you!

**Comment by yvann** [comment]
Ho yes sure ! I am going to test that and come back to you

**Comment by yvann** [comment]
OK, you were right ! I just tested and it works like a charm.

You can ignore this PR, thank you.

**Comment by smebberson** [comment]
@yvann, no worries. I'm glad you found it useful!

**Comment by yvann** [comment]
Your alpine-consul-base became my new base image ! Very convenient :)

**Pull request closed without merging**
