### PR TITLE
Add libcap package so setcap works

### PR DESCRIPTION
**Pull request by abh**

### CODE REVIEW

**Comment by smebberson** [comment]
@abh, so you're saying https://github.com/smebberson/docker-alpine/blob/master/alpine-base/Dockerfile#L18 doesn't work as it is? Which OS are you building/running these images on?

**Comment by abh** [comment]
The finished container didn’t have setcap installed. I was building it on macOS (with Docker.app), but you should be able to reproduce it I’d expect. I don’t see how it’d come into the package without this, unless alpine:3.5 has it included (it didn’t for me).

**Comment by abh** [comment]
Ping.

**Comment by smebberson** [comment]
Hey @abh, I'm just about to embark on a major point release to alpine-base so I'll be merging this in shortly and making a few other changes. Sorry for the delay (I've been busy catching up on Node.js releases https://github.com/smebberson/docker-alpine/releases).

**Comment by smebberson** [comment]
This was done in the latest version I just released :)

**Pull request closed without merging**
