### PR TITLE
Update base image to Alpine 3.5

### PR DESCRIPTION
**Pull request by abh**

### CODE REVIEW

**Comment by dchambers** [comment]
Sweet, was just about to do the same cos Alpine 3.5 has 'xclip' available in the package manager 👍

**Comment by mvdpoel** [comment]
Merge please :)

**Comment by smebberson** [comment]
Alright, I'll get this merged in :)

**Comment by lyssdod** [comment]
Can you merge it please?

**Comment by lucacri** [comment]
+1

**Comment by smebberson** [comment]
@abh, I've created v3.2.0-beta.1, https://hub.docker.com/r/smebberson/alpine-base/tags/

I added a couple of other things to the release https://github.com/smebberson/docker-alpine/commits/abh-master

You happy with those?

**Comment by smebberson** [comment]
This is all through :) Finally.

**Pull request closed without merging**
