### PR TITLE
Fix #22 by defining user shell with `-s /bin/sh`

### LINKED ISSUE #22: Incorrect shell set for consul and rabbitmq users
New users are created for `alpine-consul` and `alpine-rabbitmq`. While these accounts do work `su - consul` resulted in ```su: can't execute ':60:60:mysql:/var/lib/mysq': No such file or directory```, see
wrong shell. So new users defaulted to mysql for whatever reason. While I do not want to `su - consul` for any legitimate reason having a wrong shell is still a problem. This can be easily fixed by adding `-s /bin/sh` to the `adduser` command.

### PR DESCRIPTION
**Pull request by matthewvalimaki**
Signed-off-by: Matthew Valimaki <matthew.valimaki@gmail.com>

### CODE REVIEW

**Comment by matthewvalimaki** [comment]
I added `-g ""` to make the GECOS field be empty so that we wouldn't have ```:Linux User,,,```.

**Comment by smebberson** [comment]
@matthewvalimaki, has the merge blown away one of the commits? When I view https://github.com/smebberson/docker-alpine/pull/23/files it only shows the change to `alpine-consul/Dockerfile`, not the change to `alpine-rabbitmq/Dockerfile`?

**Comment by matthewvalimaki** [comment]
@smebberson looks like that. But not sure if we want to go with this PR or with what https://github.com/smebberson/docker-alpine/blob/master/alpine-rabbitmq/Dockerfile has `adduser -DS -G rabbitmq -s /bin/sh -h /var/lib/rabbitmq rabbitmq`.

**Comment by matthewvalimaki** [comment]
@smebberson removed my last comment as it made no sense. So it does look like one change was removed for some reason. I'll fix.

**Comment by smebberson** [comment]
@matthewvalimaki, is this PR still relevant?

**Comment by smebberson** [comment]
@matthewvalimaki, I'm closing this because I've already incorporated the changes along the way somewhere. Sorry about not merging in your PR :(

**Pull request closed without merging**
